services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cardshop
      POSTGRES_USER: cardshop
      POSTGRES_PASSWORD: cardshop_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cardshop -d cardshop"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cardshop
      - SPRING_DATASOURCE_USERNAME=cardshop
      - SPRING_DATASOURCE_PASSWORD=cardshop_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  postgres_data:
